name: social_community
description: "A new Flutter project for a Flutter hiring job"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  extensionresoft: ^0.0.6
  flutter_screenutil: ^5.9.1
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/
   - assets/img/
   - assets/svg/

  fonts:
   - family: Proxima Nova
     fonts:
       - asset: fonts/Proxima-Nova-Regular.otf
         weight: 400
         style: normal
       - asset: fonts/Proxima-Nova-Italic.otf
         style: italic
       - asset: fonts/Proxima-Nova-Black.otf
         weight: 900
       - asset: fonts/Proxima-Nova-ExtraBold.otf
         weight: 800
       - asset: fonts/Proxima-Nova-Bold.otf
         weight: 700
       - asset: fonts/Proxima-Nova-SemiBold.otf
         weight: 600
       - asset: fonts/Proxima-Nova-Light.otf
         weight: 300
       - asset: fonts/Proxima-Nova-Thin.otf
         weight: 100

