name: social_community
description: "A new Flutter project for a Flutter hiring job"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  extensionresoft: ^0.0.6
  flutter_screenutil: ^5.9.1
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/
   - assets/img/
   - assets/svg/

  fonts:
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Regular.ttf
         weight: 400
         style: normal
       - asset: fonts/Poppins-Italic.ttf
         style: italic
       - asset: fonts/Poppins-Black.ttf
         weight: 900
       - asset: fonts/Poppins-ExtraBold.ttf
         weight: 800
       - asset: fonts/Poppins-Bold.ttf
         weight: 700
       - asset: fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: fonts/Poppins-Medium.ttf
         weight: 500
       - asset: fonts/Poppins-Light.ttf
         weight: 300
       - asset: fonts/Poppins-ExtraLight.ttf
         weight: 200
       - asset: fonts/Poppins-Thin.ttf
         weight: 100

